# Dependencies
markdown: kramdown
highlighter: pygments

# Permalinks
# permalink:        pretty
# relative_permalinks: true

# Setup
title:            'Yiling Huo'
tagline:          'PhD student | Linguistics | University College London'
description: >
  Hi! I'm Yiling, and this is my personal website. I'm interested in how the human mind processes language.

# url:              http://hyde.getpoole.com
# baseurl:          /

# author:
#   name:           'Yiling Huo'
#   url:            https://twitter.com/mdo

paginate:         5

# Custom vars
# version:          2.1.0

# github:
#   repo:           https://github.com/poole/hyde

hyde-theme:
  skin: autumn

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate

header_pages:
 - publications.md
 - teaching.md
 - tutorials/index.md
 - gist
 - games.html
 - photography.html
 - links.html

# Social links in sidebar
social_links:
  - { platform: email,        user_url: "mailto:yiling.huo.18@ucl.ac.uk" }
  - { platform: twitter,        user_url: "https://twitter.com/YlHuo" }
  - { platform: github,         user_url: "https://github.com/Yiling-Huo" }
  - { platform: gist,         user_url: "https://gist.github.com/Yiling-Huo" }
  - { platform: orcid,        user_url: "https://orcid.org/0000-0002-9327-9412" }
  - { platform: linkedin,        user_url: "https://www.linkedin.com/in/yiling-huo-5b4228244/" }

# Correct time zone for updating blog
timezone: Europe/London