name: Update Season skin

# Define the trigger for the workflow
on:
  schedule:
    - cron: '0 0 1 3,6,9,12 *' # Run at midnight on the 1st of March, June, September, and December

permissions:
  contents: write

jobs:
  advance-season:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Advance a season
        id: advance_season
        run: |
          current_season=$(awk '/hyde-theme:/ {getline; print}' _config.yml | awk '{print $2}')
          echo "Current season: $current_season"
          next_season=$(bash script/advance_season.sh "$current_season")
          sed -i '/hyde-theme:/ {n; s/skin: .*/skin: '$next_season'/}' _config.yml

      - name: Commit and Push Changes
        run: |
          git config user.name ${{ secrets.MY_NAME }}
          git config user.email ${{ secrets.MY_EMAIL }}
          git add _config.yml
          git commit -m "Advance to the next season"
          git push origin master
