name: Update Season skin

# Define the trigger for the workflow
on:
  schedule:
    - cron: '*/5 * * * *'

env:
  TZ: 'UTC' # set the timezone environment to UTC for the duration of the workflow run. Because GitHub Actions runners typically use the UTC time. 

jobs:
  update-config:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Determine Current Season
      id: get_season
      run: |
        season=$(bash script/get_season.sh)
        echo "::set-output name=season::$season"

    - name: Modify Config
      run: |
        season=$(echo "${{ steps.get_season.outputs.season }}")
        sed -i 's/minima:\s*skin:\s*.*/minima: skin: '$season'/' _config.yml

    - name: Commit and Push Changes
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add _config.yaml
        git commit -m "Update 'skin' variable based on current season"
        git push