name: Update Season skin

# Define the trigger for the workflow
on:
  schedule:
    - cron: '0 0 1 3,6,9,12 *' # Run at midnight on the 1st of March, June, September, and December
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: write

jobs:
  advance-season:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Advance a season
        id: advance_season
        run: |
          current_season=$(awk '/hyde-theme:/ {getline; print}' _config.yml | awk '{print $2}')
          echo "Current season: $current_season"
          next_season=$(bash script/advance_season.sh "$current_season")
          sed -i '/hyde-theme:/ {n; s/skin: .*/skin: '$next_season'/}' _config.yml

      - name: Commit and Push
        env:
          PERSONAL_ACCESS_TOKEN: ${{ secrets.PAT }}
        run: |
          git config user.name "${{ secrets.MY_NAME }}" # Used for the commit author
          git config user.email "${{ secrets.MY_EMAIL }}" # Used for the commit author's email
          git add _config.yml
          git commit -m "Advance to the next season"
          # Authenticate using the PAT
          git remote set-url origin https://x-access-token:${PERSONAL_ACCESS_TOKEN}@github.com/yiling-huo/yiling-huo.github.io.git
          git push origin master
